
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: Epicatomic
subtitle: "All big ideas start small"
url: "https://thomascmost.github.io" # the base hostname & protocol for your site
# baseurl: "/the/subpath/of/your/site" # Set this value to "" if you want your site to be root
baseurl: "/epicatomic"
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: engineering
    desc: "Posts describing engineering & software projects"

  - cat: theater
    desc: "Posts about theater & performance projects"

  - cat: writing
    desc: "Posts about writing, both fiction and non-fiction"
